### ISSUE TITLE
[Brainstorming] - Roadmap

### ISSUE THREAD

**Issue by awmatheson** [Azure/aml-run#11]
# Feature brainstorming for GH integration
- [x] Pass model back to artifact in actions
- [x] Make a release flag so that the model will be made into a release automatically. 
- [x] Create a docker image of the model

**Comment by marvinbuss** [comment]
Added as individual issues
